"""AI backends for chai.

Each module in this package exposes a single ``*Component`` class. Two
exported lists drive how role-mixin classes (``GeminiTranscriber``,
``LMStudioClassifier``, ``VLLMSegmenter`` ...) are auto-generated:

* ``__all__`` -- components that get composite classes auto-generated by
  :func:`create_all_components` (consumed by ``chai.transcriber``,
  ``chai.classifier``, etc.).
* ``__more_than_all__`` -- components that are exported and importable but
  intentionally skipped by the auto-generator (e.g. ``TransformersComponent``,
  which loads heavy local weights and is wired up via explicit subclasses).

Optional backends whose dependencies are platform-specific or heavy are
registered defensively so importing ``chai.ai`` keeps working when a
backend's deps aren't installed -- e.g. ``mlx-vlm`` only exists on Apple
Silicon, and the ``openai`` client may not be installed at all.
"""

import logging

logger = logging.getLogger("chai")

from .gemini import GeminiComponent
from .lm_studio import LMStudioComponent
from .ollama import OllamaComponent
from .openai import OpenAIComponent
from .transformers import TransformersComponent

__all__ = [GeminiComponent, LMStudioComponent, OllamaComponent, OpenAIComponent]

__more_than_all__ = [TransformersComponent]

# Thin OpenAI subclasses (vLLM, sglang) -- present only if their server
# client deps are importable. Same for in-process MLX-VLM (Apple Silicon).
try:
    from .vllm import VLLMComponent

    __all__.append(VLLMComponent)
except ImportError as e:  # pragma: no cover -- depends on env
    logger.warning(f"VLLMComponent unavailable: {e}")

try:
    from .sglang import SGLangComponent

    __all__.append(SGLangComponent)
except ImportError as e:  # pragma: no cover -- depends on env
    logger.warning(f"SGLangComponent unavailable: {e}")

try:
    from .mlx_vlm import MLXVLMComponent

    __all__.append(MLXVLMComponent)
except ImportError as e:  # pragma: no cover -- Apple Silicon only
    logger.info(f"MLXVLMComponent unavailable on this platform: {e}")


def create_all_components(base_class: type) -> dict:
    """Generate one composite class per backend in ``__all__`` for a given role base class.

    Called at import time by the role modules (``chai.transcriber``, ``chai.classifier``, ...), which
    splat the returned ``{name: class}`` dict into their module globals. Names are formed as
    ``<Backend><Role>``, e.g. ``GeminiTranscriber`` from ``GeminiComponent`` + ``Transcriber``.
    """
    clss = {}
    for ai_class in __all__:
        name = f"{ai_class.__name__.replace('Component', '')}{base_class.__name__}"
        new = create_ai_component(name, base_class, ai_class)
        clss[name] = new
    dispatcher_name = f"AI{base_class.__name__}"
    clss[dispatcher_name] = create_ai_dispatcher(dispatcher_name, base_class, clss)
    return clss


def available_services() -> dict:
    """Map of service name -> backend Component class for the importable backends.

    ``custom`` is an alias for the OpenAI-compatible backend (point it at any
    server with ``api_host``); ``mlx_vlm`` aliases ``mlxvlm``.
    """
    services = {}
    for ai_class in __all__:
        services[ai_class.__name__.replace("Component", "").lower()] = ai_class
    if "openai" in services:
        services["custom"] = services["openai"]
    if "mlxvlm" in services:
        services["mlx_vlm"] = services["mlxvlm"]
    return services


def create_ai_dispatcher(name: str, base_class: type, composites: dict) -> type:
    """Generate the service-selectable ``AI<Role>`` class (e.g. ``AITranscriber``).

    One palette node for the whole role: the ``service`` setting picks the backend at construction
    time, so instantiating ``AITranscriber`` with ``{"service": "ollama"}`` actually returns an
    ``OllamaTranscriber``. All other settings (``model``, ``prompt``, ``api_host``, ...) pass through
    to the chosen backend, which supplies its own model default.

    Settings:
        - service: AI backend to use: gemini | lmstudio | ollama | openai | custom (an OpenAI-compatible endpoint, set api_host) | vllm | sglang | mlx_vlm (default gemini)
        - model: model id for the chosen service (each service has a sensible default)
        - prompt: prompt template, passed through to the backend
        - api_host: server host:port for local/custom services
    """

    def __new__(cls, tree, workflow, parent=None):
        service = str(tree.get("settings", {}).get("service", "gemini")).lower().strip()
        ai_class = available_services().get(service)
        if ai_class is None:
            raise ValueError(
                f"Unknown AI service {service!r} for {name}; available: {sorted(available_services())}"
            )
        target = composites.get(f"{ai_class.__name__.replace('Component', '')}{base_class.__name__}")
        if target is None:
            raise ValueError(f"Service {service!r} has no {base_class.__name__} composite available")
        inst = object.__new__(target)
        # The target composite is not a subclass of the dispatcher, so Python
        # will not call __init__ for us after __new__ -- do it explicitly.
        inst.__init__(tree, workflow, parent)
        return inst

    doc = f"""Service-selectable AI {base_class.__name__.lower()}: one node for every AI backend.

    Pick the backend with the ``service`` setting -- constructing this class actually returns the
    matching composite (e.g. ``service: ollama`` -> ``Ollama{base_class.__name__}``). All other
    settings pass through to the chosen backend.

    Settings:
        - service: gemini | lmstudio | ollama | openai | custom (OpenAI-compatible endpoint, set api_host) | vllm | sglang | mlx_vlm (default gemini)
        - model: model id for the chosen service (each service has a sensible default)
        - prompt: prompt template, passed through to the backend
        - api_host: server host:port for local/custom services
    """
    return type(
        name,
        (base_class,),
        {"__new__": __new__, "__module__": base_class.__module__, "__doc__": doc},
    )


def create_ai_component(name: str, base_class: type, ai_class: type) -> type:
    """
    Dynamically generates a composite AI component class (e.g. GeminiSegmenter).
    This avoids having to hand-craft boilerplate multiple inheritance classes.

    The generated class inherits ``(base_class, ai_class)``. Its ``__init__`` runs the AI backend's
    initializer first (which reaches ``Component.__init__`` via super), then the role base's
    ``__init__`` for role defaults like the fallback prompt -- ``Component.__init__``'s
    already-initialized guard prevents double initialization. ``_process`` always delegates to the AI
    backend, so the composite takes the role's name/prompt defaults but the backend's behaviour.
    """

    def __init__(self, tree, workflow, parent=None):
        # Initialize the AI class first (this usually calls Component.__init__ via super)
        ai_class.__init__(self, tree, workflow, parent)

        # Initialize the base class if it has its own __init__ logic
        # (e.g., to set expected defaults or specific properties)
        # We avoid object.__init__ or Component.__init__ to prevent double-initialization
        if "Component" not in base_class.__name__ and base_class.__init__ is not object.__init__:
            try:
                base_class.__init__(self, tree, workflow, parent)
            except TypeError:
                pass

    def _process(self, input):
        # AI composite classes always delegate their core processing to the AI implementation
        return ai_class._process(self, input)

    return type(
        name,
        (base_class, ai_class),
        {
            "__init__": __init__,
            "_process": _process,
            "__module__": base_class.__module__,
            # Marks machine-generated per-backend composites so UIs can hide
            # them behind the service-selectable AI<Role> dispatcher.
            "_chai_generated": True,
        },
    )
